// <auto-generated />
namespace XenonCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SitePageaddParentandChildnavigationTexttoLinkText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SitePageaddParentandChildnavigationTexttoLinkText));
        
        string IMigrationMetadata.Id
        {
            get { return "201509202308219_SitePage add Parent and Child navigation, Text to LinkText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
